# Variables that can be put on the X and Y axes
axis_vars <- c(
    "Points per game" = "PTS",
    "Rebounds per game" = "TRB",
    "Offensive rebounds per game" = "ORB",
    "Defensive rebounds per game" = "DRB",
    "Assists per game" = "AST",
    "Steals per game" = "STL",
    "Blocks per game" = "BLK",
    "Effective field goal pct" = "eFGP",
    "Field goals made per game" = "FG",
    "Field goals attempts per game" = "FGA",
    "Field goal pct" = "FGP",
    "3 points shots made per game" = "TH",
    "3 points shots attempts per game" = "THA",
    "3 points shot pct" = "THP",
    "2 points shots made per game" = "TW",
    "2 points shots attempts per game" = "TWA",
    "2 points shot pct" = "TWP",
    "Free throws made per game" = "FT",
    "Free throws attempts per game" = "FTA",
    "Free throw pct" = "FTP",
    "Turnovers per game" = "TOV",
    "Fouls per game" = "PF")
